#Filename: dev.yml
version: '3.5'
services:
  app:
    command: npm start
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development