# production.yml

version: '3.5'

services:
  # command: ["nginx", "-g", "daemon off;"]
  app:
    build:
      context: .
      dockerfile: Dockerfile-production
    ports:
      - 80:80
    environment:
      - NODE_ENV=production